chore: Recoupling language server
openfga/vscode-ext pull request #48
Opened 2023-08-03 18:33 UTC by d-jeffery

## Description

## References

Coupled the example language server back up.

[openfga-vscode-0.1.0.vsix.zip](https://github.com/openfga/vscode-ext/files/12253921/openfga-vscode-0.1.0.vsix.zip)

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-08-03 19:32 UTC, d-jeffery commented on server/package.json
> +	"license": "MIT",
Will fix.

2023-08-03 19:32 UTC, d-jeffery commented on server/src/server.ts
> + * ------------------------------------------------------------------------------------------ */
Will remove

2023-08-03 19:33 UTC, adriantam requested changes

2023-08-03 19:33 UTC, adriantam commented on server/package.json
> +	"author": "Microsoft Corporation",
Please update author/version/name/description etc.

2023-08-03 19:33 UTC, adriantam commented on server/src/server.ts
> + * Copyright (c) Microsoft Corporation. All rights reserved.
Should not be copyright to Microsoft

2023-08-04 14:51 UTC, adriantam commented on .vscode/launch.json
> +			"port": 6012,
maybe add comments on why 6012?

2023-08-04 15:01 UTC, adriantam approved these changes

2023-08-04 15:01 UTC, merged